name: Build and Release .NET AOT Project

on:
  workflow_dispatch: 
  push:
    branches:
      - main  
    tags: 
      - 'v*'
    paths: 
      - '**/*.cs'
      - '**/*.csproj'
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish Native AOT
      run: dotnet publish -r win-x64 -c Release --self-contained true -o ./publish

    - name: Rename executable
      run: |
        mv ./publish/rn_resource_checker.exe ./publish/rn_resource_checker_win_x64.exe

    - name: Release Asset
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./publish/rn_resource_checker_win_x64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}